Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/falcon/api.py", line 182, in __call__
    responder(req, resp, **params)
  File "/root/catch_video/restapi.py", line 30, in on_post
    raise falcon.HTTPBadRequest('bad req')
TypeError: __init__() takes exactly 3 arguments (2 given)
[2015-05-28 10:43:21 +0000] [10595] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/falcon/api.py", line 182, in __call__
    responder(req, resp, **params)
  File "/root/catch_video/restapi.py", line 30, in on_post
    raise falcon.HTTPBadRequest('bad req')
TypeError: __init__() takes exactly 3 arguments (2 given)
